import { expect, test, type Page } from '@playwright/test'

async function install(page: Page) {
  await page.goto('/')
  await expect(page.getByText('辞書データを準備しています')).toBeVisible()
  await expect(page.getByText('学習の現在地')).toBeVisible({ timeout: 20_000 })
}

test('setup, search, expression selection, study, stats and backup', async ({ page, browserName }) => {
  await install(page)
  await page.getByRole('button', { name: '単語を追加' }).click()
  await page.getByLabel('検索する英単語').fill('account')
  await page.getByRole('button', { name: '検索' }).click()
  await expect(page.getByRole('heading', { name: 'account' })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: /account for/ })).toBeVisible()
  await page.getByRole('checkbox', { name: /take into account/ }).uncheck()
  await expect(page.getByText('account to the stars', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'この単語を学習する' }).click()
  await page.getByRole('button', { name: '学習', exact: true }).click()
  await expect(page.getByText('FIRST STUDY')).toBeVisible()
  await page.getByRole('button', { name: '覚える' }).click()
  await page.getByLabel('答え').fill('account')
  await page.getByRole('button', { name: '回答' }).click()
  await expect(page.getByRole('heading', { name: 'Correct' })).toBeVisible()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByText('FIRST STUDY')).toBeVisible()
  await page.getByRole('button', { name: '覚える' }).click()
  await page.getByRole('button', { name: 'Hint' }).click()
  await page.getByLabel('答え').fill('wrong')
  await page.getByRole('button', { name: '回答' }).click()
  await expect(page.getByText('Correct answer')).toBeVisible()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('heading', { name: '今日の復習終了' })).toBeVisible()
  await page.getByRole('button', { name: 'ホーム' }).click()
  await expect(page.getByText('1 / 2 定着')).toHaveCount(0)
  await page.getByRole('button', { name: '統計' }).click()
  await expect(page.getByText('総登録単語')).toBeVisible()
  await expect(page.getByText('総復習回数').locator('..')).toContainText('2')
  await page.getByRole('button', { name: '設定' }).click()
  if (browserName === 'chromium') {
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: '学習データをバックアップ' }).click()
    const download = await downloadPromise
    expect(download.suggestedFilename()).toContain('word-recall-backup')
    const savedPath = await download.path()
    expect(savedPath).not.toBeNull()
    await page.locator('input[type=file]').setInputFiles(savedPath!)
    await expect(page.getByRole('status')).toContainText('バックアップを復元しました')
  } else {
    await page.getByRole('button', { name: '学習データをバックアップ' }).click()
    await expect(page.getByRole('status')).toContainText(/バックアップ/)
  }
})

test('offline reload keeps search, study, stats and details available', async ({ page, context, browserName }) => {
  test.skip(browserName === 'webkit', 'Playwright WebKit offline reload is not supported reliably; WebKit UI is covered by the full flow.')
  await install(page)
  await page.getByRole('button', { name: '単語を追加' }).click()
  await page.getByLabel('検索する英単語').fill('meticulous')
  await page.getByRole('button', { name: '検索' }).click()
  await page.getByRole('button', { name: 'この単語を学習する' }).click()
  await page.waitForTimeout(1000)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByText('学習の現在地')).toBeVisible()
  await page.getByRole('button', { name: '単語', exact: true }).click()
  await expect(page.getByText('meticulous')).toBeVisible()
  await page.getByText('meticulous').click()
  await expect(page.getByText('showing great attention to detail')).toBeVisible()
  await page.getByRole('button', { name: '統計' }).click()
  await expect(page.getByText('総登録単語')).toBeVisible()
})
