import { useEffect, useRef, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { ensureSettings, userDb } from '../db/userDb'
import { downloadBackup, restoreBackup } from '../services/backupService'

export function SettingsPage() {
  const settings = useLiveQuery(() => ensureSettings(), []); const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(''); const [storage, setStorage] = useState<string>('取得できません')
  useEffect(() => { if (navigator.storage?.estimate) void navigator.storage.estimate().then((x) => setStorage(`${formatBytes(x.usage ?? 0)} / ${formatBytes(x.quota ?? 0)}`)) }, [])
  if (!settings) return <main className="page"><div className="skeleton tall"/></main>
  async function patch(changes: Partial<typeof settings>) { await userDb.appSettings.put({ ...settings!, ...changes }) }
  async function restore(file: File) { try { const parsed: unknown = JSON.parse(await file.text()); await restoreBackup(parsed); setMessage('バックアップを復元しました') } catch { setMessage('バックアップが不正です。既存データは変更されていません。') } }
  return <main className="page settings-page"><header><p className="eyebrow">PREFERENCES</p><h1>設定</h1></header><section className="settings-section"><h2>学習</h2><label>単語帳でここまで見た単語数<input type="number" min="0" inputMode="numeric" value={settings.totalEncounteredWords ?? ''} onChange={(e) => void patch({ totalEncounteredWords: e.target.value === '' ? null : Math.max(0, Number(e.target.value)) })}/></label><label>目標記憶率 <strong>{Math.round(settings.desiredRetention * 100)}%</strong><input type="range" min="0.8" max="0.97" step="0.01" value={settings.desiredRetention} onChange={(e) => void patch({ desiredRetention: Number(e.target.value) })}/></label><label>定着判定のStability <strong>{settings.masteryStabilityDays}日</strong><input type="range" min="14" max="90" step="1" value={settings.masteryStabilityDays} onChange={(e) => void patch({ masteryStabilityDays: Number(e.target.value) })}/></label></section><section className="settings-section"><h2>バックアップ</h2><p className="muted">最終バックアップ：{settings.lastBackupAt ? new Intl.DateTimeFormat('ja-JP').format(new Date(settings.lastBackupAt)) : 'まだありません'}</p><button className="secondary full" onClick={() => void downloadBackup().then(() => setMessage('バックアップを作成しました')).catch(() => setMessage('バックアップを保存できませんでした'))}>学習データをバックアップ</button><button className="secondary full" onClick={() => input.current?.click()}>バックアップを復元</button><input ref={input} hidden type="file" accept="application/json,.json" onChange={(e) => { const f = e.target.files?.[0]; if (f) void restore(f); e.target.value = '' }}/></section><section className="settings-section"><h2>ストレージ</h2><dl><div><dt>アプリ使用容量 / 上限</dt><dd>{storage}</dd></div><div><dt>辞書バージョン</dt><dd>{settings.dictionaryVersion ?? '未設定'}</dd></div></dl></section><section className="settings-section"><h2>プライバシー</h2><p>学習データはこの端末内に保存されます。分析・トラッキング・外部送信は行いません。</p></section><section className="settings-section"><h2>データソースとライセンス</h2><p>CEFR-J、Octanove、DiQt、PHRASE、PHaVE、English Wiktionary / Kaikki / Wiktextract、ts-fsrs。詳細は同梱の LICENSES.md と THIRD_PARTY_NOTICES.md を参照してください。</p></section>{message && <div className="toast" role="status">{message}</div>}</main>
}
function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 ** 2) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 ** 2).toFixed(1)} MB` }
