import { useMemo, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { userDb } from '../db/userDb'
import type { UserWord } from '../types'

type Filter = 'all' | 'learning' | 'mastered' | 'overdue' | 'recent'
export function WordsPage({ onAdd, onSelect }: { onAdd: () => void; onSelect: (word: UserWord) => void }) {
  const rows = useLiveQuery(async () => { const words = await userDb.userWords.toArray(); const cards = await userDb.studyCards.where('targetType').equals('word').toArray(); return words.map((word) => ({ word, card: cards.find((c) => c.targetId === word.id) })) }, [])
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<Filter>('all'); const [sort, setSort] = useState<'added' | 'alpha' | 'due' | 'stability'>('added')
  const shown = useMemo(() => (rows ?? []).filter(({ word, card }) => word.lemma.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'learning' && !card?.mastered) || (filter === 'mastered' && card?.mastered) || (filter === 'overdue' && card && new Date(card.fsrsCardData.due) < new Date()) || (filter === 'recent' && Date.now() - new Date(word.addedAt).getTime() < 7 * 86_400_000))).sort((a, b) => sort === 'alpha' ? a.word.lemma.localeCompare(b.word.lemma) : sort === 'due' ? (a.card?.fsrsCardData.due ?? '').localeCompare(b.card?.fsrsCardData.due ?? '') : sort === 'stability' ? (b.card?.fsrsCardData.stability ?? 0) - (a.card?.fsrsCardData.stability ?? 0) : b.word.addedAt.localeCompare(a.word.addedAt)), [rows, query, filter, sort])
  return <main className="page"><header className="title-row"><div><p className="eyebrow">LIBRARY</p><h1>単語</h1></div><button className="round-add" onClick={onAdd} aria-label="単語を追加">＋</button></header><input className="library-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="単語を検索" aria-label="登録単語を検索"/><div className="filter-scroll">{([['all','すべて'],['learning','学習中'],['mastered','定着'],['overdue','期限超過'],['recent','最近追加']] as const).map(([key,label]) => <button className={filter === key ? 'selected' : ''} onClick={() => setFilter(key)} key={key}>{label}</button>)}</div><label className="sort-control">並び順<select value={sort} onChange={(e) => setSort(e.target.value as typeof sort)}><option value="added">追加日</option><option value="alpha">アルファベット</option><option value="due">次回復習</option><option value="stability">Stability</option></select></label><section className="word-list">{shown.map(({ word, card }) => <button key={word.id} onClick={() => onSelect(word)}><span><strong>{word.lemma}</strong><small>{word.sourceStatus === 'userProvided' ? 'ユーザー入力' : word.sourceStatus}</small></span><span className={card?.mastered ? 'status mastered' : 'status'}>{card?.mastered ? '定着' : '学習中'}</span></button>)}{shown.length === 0 && <div className="empty-list"><p>表示する単語がありません。</p><button onClick={onAdd}>単語を追加</button></div>}</section></main>
}
